// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-FUsSilOBUFlyc3HL3U_XH7n_K9w-i6g',
    appId: '1:942103513813:web:8bfdd0d9e68cafbd1fb05c',
    messagingSenderId: '942103513813',
    projectId: 'digital-trainer-2f2c9',
    authDomain: 'digital-trainer-2f2c9.firebaseapp.com',
    storageBucket: 'digital-trainer-2f2c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rDKPZ6l0IYj8OAo1J7GxsR6Cd9B9G00',
    appId: '1:942103513813:android:a58e26b53d13d21c1fb05c',
    messagingSenderId: '942103513813',
    projectId: 'digital-trainer-2f2c9',
    storageBucket: 'digital-trainer-2f2c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUIF-gdXe7cqGuzWngMYC3qmVdBQFeplU',
    appId: '1:942103513813:ios:a3f1a87f4ecc5c151fb05c',
    messagingSenderId: '942103513813',
    projectId: 'digital-trainer-2f2c9',
    storageBucket: 'digital-trainer-2f2c9.firebasestorage.app',
    iosClientId: '942103513813-4a89a7lgloghopmta0ltco97srond686.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalTrainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUIF-gdXe7cqGuzWngMYC3qmVdBQFeplU',
    appId: '1:942103513813:ios:a3f1a87f4ecc5c151fb05c',
    messagingSenderId: '942103513813',
    projectId: 'digital-trainer-2f2c9',
    storageBucket: 'digital-trainer-2f2c9.firebasestorage.app',
    iosClientId: '942103513813-4a89a7lgloghopmta0ltco97srond686.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalTrainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-FUsSilOBUFlyc3HL3U_XH7n_K9w-i6g',
    appId: '1:942103513813:web:4cb0e37d02b5d61c1fb05c',
    messagingSenderId: '942103513813',
    projectId: 'digital-trainer-2f2c9',
    authDomain: 'digital-trainer-2f2c9.firebaseapp.com',
    storageBucket: 'digital-trainer-2f2c9.firebasestorage.app',
  );
}
